from cmu_graphics import *
from theme import drawPokerTableBackground, drawPixelText
from button import Button
from card import *

class Blackjack:
    def __init__(self):
        self.deck = Deck(numDecks=6)
        self.playerHand = Hand()
        self.dealerHand = Hand()
        self.chips = 500
        self.bet = 0
        self.gamePhase = 'betting'  # betting, playing, dealerTurn, result
        self.resultMessage = ''
        cx = app.width / 2
        self.buttons = [
            Button('HIT', cx - 150, app.height * 0.88, 120, 44, rgb(180, 50, 50), rgb(220, 80, 80)),
            Button('STAND', cx, app.height * 0.88, 120, 44, rgb(50, 50, 180), rgb(80, 80, 220)),
            Button('DOUBLE', cx + 150, app.height * 0.88, 120, 44, rgb(180, 140, 30), rgb(220, 180, 60)),
            Button('MENU', 100, app.height * 0.05, 80, 36, rgb(100, 100, 100), rgb(140, 140, 140)),
        ]
        self.betButtons = [
            Button('$10', cx - 130, app.height * 0.76, 80, 40, rgb(180, 50, 50), rgb(220, 80, 80)),
            Button('$25', cx, app.height * 0.76, 80, 40, rgb(50, 50, 180), rgb(80, 80, 220)),
            Button('$50', cx + 130, app.height * 0.76, 80, 40, rgb(50, 150, 80), rgb(80, 180, 110)),
            Button('DEAL', cx, app.height * 0.85, 120, 44, rgb(180, 140, 30), rgb(220, 180, 60)),
        ]

    # all renderings generated by Claude
    def render(self, app):
        drawPokerTableBackground(app)
        cx = app.width / 2
        
        # Dealer zone
        drawPixelText('DEALER', cx, app.height * 0.12, rgb(180, 140, 60), scale=1.2)
        drawRect(cx - app.width * 0.25, app.height * 0.16, app.width * 0.5, 2, fill=rgb(180, 140, 60))

        # Dealer card slots
        for i in range(2):
            x = cx - 70 + i * 80
            drawRect(x, app.height * 0.19, 60, 84, fill=None,
                    border=rgb(180, 140, 60), borderWidth=1, opacity=40)
        
        # Table info
        drawPixelText('BLACKJACK PAYS 3 TO 2', cx, app.height * 0.38,
                    rgb(180, 50, 50), scale=0.8)
        drawPixelText('Dealer stands on 17', cx, app.height * 0.42,
                    rgb(150, 150, 130), scale=0.7)
        
        # Divider
        drawRect(cx - app.width * 0.25, app.height * 0.46, app.width * 0.5, 2, fill=rgb(180, 140, 60))
        
        # Player zone
        drawPixelText('YOUR HAND', cx, app.height * 0.5, rgb(180, 140, 60), scale=1)
        
        # Player card slots
        for i in range(2):
            x = cx - 70 + i * 80
            drawRect(x, app.height * 0.53, 60, 84, fill=None,
                    border=rgb(180, 140, 60), borderWidth=1, opacity=40)
        
        # Chips display
        drawPixelText(f'CHIPS: ${self.chips}', app.width - 120, app.height * 0.05,
                    rgb(255, 230, 150), scale=1)
        
        # Phase-specific rendering
        if self.gamePhase == 'betting':
            drawPixelText('PLACE YOUR BET', cx, app.height * 0.7,
                        rgb(255, 230, 150), scale=1.2)
            if self.bet > 0:
                drawPixelText(f'Current bet: ${self.bet}', cx, app.height * 0.75,
                            rgb(200, 200, 180), scale=0.9)
            for button in self.betButtons:
                button.render()
        
        elif self.gamePhase == 'playing':
            self.renderDealerCards(app)
            self.renderPlayerCards(app)
            drawPixelText(f'Hand: {self.getHandValue(self.playerHand)}',
                        cx, app.height * 0.7, rgb(255, 230, 150), scale=1)
            drawPixelText(f'Bet: ${self.bet}', cx, app.height * 0.75,
                        rgb(200, 200, 180), scale=0.8)
            for button in self.buttons:
                button.render()
        
        elif self.gamePhase == 'result':
            self.renderDealerCards(app)
            self.renderPlayerCards(app)
            drawRect(cx - 200, app.height * 0.78, 400, 50, fill=rgb(140, 20, 20))
            drawRect(cx - 198, app.height * 0.78 + 2, 396, 46, fill=rgb(180, 30, 30))
            drawPixelText(self.resultMessage, cx, app.height * 0.78 + 25,
                        rgb(255, 230, 150), scale=1.2)

    def renderDealerCards(self, app):
        cards = self.dealerHand.getCards()
        startX = app.width / 2 - (len(cards) * 40)
        for i, card in enumerate(cards):
            x = startX + i * 80
            card.render(x, 100)

    def renderPlayerCards(self, app):
        cards = self.playerHand.getCards()
        startX = app.width / 2 - (len(cards) * 40)
        for i, card in enumerate(cards):
            x = startX + i * 80
            card.render(x, 290)

    def getHandValue(self, hand):
        value = 0
        aces = 0
        for card in hand.getCards():
            if card.name in ['Jack', 'Queen', 'King']:
                value += 10
            elif card.name == 'Ace':
                value += 11
                aces += 1
            else:
                value += int(card.name)
        while value > 21 and aces > 0:
            value -= 10
            aces -= 1
        return value

    def handleClick(self, app, mouseX, mouseY):
        pass