from cmu_graphics import *

# button functionality for easier button making
class Button:
    def __init__(self, label, x, y, width, height, color, lightColor=None):
        self.label = label
        self.x = x
        self.y = y
        self.width = width
        self.height = height
        self.pressed = False
        self.color = color
        self.lightColor = lightColor if lightColor else color

    def isClicked(self, mouseX, mouseY):
        return ((self.x - self.width / 2 < mouseX < self.x + self.width / 2) and 
                (self.y - self.height / 2 < mouseY < self.y + self.height / 2))
    
    # function generated by Claude
    def render(self):
        w = self.width
        h = self.height
        
        # Offset when pressed — button moves down onto its shadow
        offset = 3 if self.pressed else 0
        
        x = self.x - w / 2
        y = self.y - h / 2

        # Shadow (stays in place)
        drawRect(x + 4, y + 4, w, h, fill=rgb(0, 0, 0), opacity=40)
        # Dark body (shifts down when pressed)
        drawRect(x + offset, y + offset, w, h, fill=self.color)
        # Light body inset
        drawRect(x + 2 + offset, y + 2 + offset, w - 4, h - 4, fill=self.lightColor)
        # Highlight on top edge
        drawRect(x + 2 + offset, y + 2 + offset, w - 4, 4, fill='white', opacity=30)
        # Gold pixel border
        drawRect(x + offset, y + offset, w, 2, fill=rgb(200, 160, 50))
        drawRect(x + offset, y + h - 2 + offset, w, 2, fill=rgb(200, 160, 50))
        drawRect(x + offset, y + offset, 2, h, fill=rgb(200, 160, 50))
        drawRect(x + w - 2 + offset, y + offset, 2, h, fill=rgb(200, 160, 50))
        # Label
        drawLabel(self.label, self.x + offset, self.y + offset, 
                  size=22, bold=True, fill=rgb(255, 240, 200), font='monospace')
    