from cmu_graphics import *
from card import *
from button import *
from war import *
from blackjack import *
from gofish import *
from theme import *

def onAppStart(app):
    app.screenMode = 'menu'
    app.width = 800
    app.height = 600
    app.warGame = None
    app.blackjackGame = None
    app.goFishGame = None
    app.menuButtons = [
        Button('WAR', app.width/2, 290, 260, 56, 
           rgb(180, 50, 50), rgb(220, 80, 80)),
        Button('BLACKJACK', app.width/2, 370, 260, 56, 
           rgb(50, 50, 180), rgb(80, 80, 220)),
        Button('GO FISH', app.width/2, 450, 260, 56, 
           rgb(50, 150, 80), rgb(80, 180, 110)),
]

def handleMenuButtons(app, button):
    if button.label == 'WAR':
        app.warGame = WarGame()
        app.screenMode = 'war'
    elif button.label == 'BLACKJACK':
        app.blackjackGame = BlackjackGame()
        app.screenMode = 'blackjack'
    elif button.label == 'GO FISH':
        app.goFishGame = GoFishGame()
        app.screenMode = 'gofish'

def redrawAll(app):
    drawScreen(app)

# function generated by Claude
def onMousePress(app, mouseX, mouseY):
    if app.screenMode == 'menu':
        for button in app.menuButtons:
            if button.isClicked(mouseX, mouseY):
                button.pressed = True
    elif app.screenMode == 'war':
        app.warGame.handleClick(app, mouseX, mouseY)
    elif app.screenMode == 'blackjack':
        app.blackjackGame.handleClick(app, mouseX, mouseY)
    elif app.screenMode == 'gofish':
        app.goFishGame.handleClick(app, mouseX, mouseY)

# function generated by Claude
def onMouseRelease(app, mouseX, mouseY):
    if app.screenMode == 'menu':
        for button in app.menuButtons:
            if button.pressed and button.isClicked(mouseX, mouseY):
                handleMenuButtons(app, button)
            button.pressed = False

def onKeyPress(app, key):
    pass

def onStep(app):
    pass

def drawScreen(app):
    if app.screenMode == 'menu':
        drawMenu(app)
    elif app.screenMode == 'rules':
        drawRulesScreen(app)
    elif app.screenMode == 'war':
        app.warGame.render(app)
    elif app.screenMode == 'blackjack':
        app.blackjackGame.render(app)
    elif app.screenMode == 'gofish':
        app.goFishGame.render(app)

def drawMenu(app):
    drawMenuScreen(app)
    for button in app.menuButtons:
        button.render()

def drawRulesScreen(app):
    pass

def main():
    runApp()

main()