from cmu_graphics import *
from card import *
from button import *
from war import *
from blackjack import *
from gofish import *
from theme import *
# add game imports once i write them

def onAppStart(app):
    app.screenMode = 'menu'
    app.tag = 'log'
    app.warGame = None
    app.blackjackGame = None
    app.goFishGame = None
    app.menuButtons = [
        Button('War', 200, 200, 150, 50),
        Button('Blackjack', 200, 280, 150, 50),
        Button('Go Fish', 200, 360, 150, 50),
    ]

def handleMenuButtons(app, button):
    if button.label == 'War':
        app.warGame = WarGame()
        app.screenMode = 'war'
        app.tag = 'game'
    elif button.label == 'Blackjack':
        app.blackjackGame = BlackjackGame()
        app.screenMode = 'blackjack'
        app.tag = 'game'
    elif button.label == 'Go Fish':
        app.goFishGame = GoFishGame()
        app.screenMode = 'gofish'
        app.tag = 'game'

def redrawAll(app):
    drawScreen(app)

# function generated by Claude
def onMousePress(app, mouseX, mouseY):
    if app.screenMode == 'menu':
        for button in app.menuButtons:
            if button.isClicked(mouseX, mouseY):
                handleMenuButton(app, button)
    elif app.screenMode == 'war':
        app.warGame.handleClick(app, mouseX, mouseY)
    elif app.screenMode == 'blackjack':
        app.blackjackGame.handleClick(app, mouseX, mouseY)
    elif app.screenMode == 'gofish':
        app.goFishGame.handleClick(app, mouseX, mouseY)

def onKeyPress(app, key):
    pass

def onStep(app):
    pass

def drawScreen(app):
    if app.tag == 'log':
        if app.screenmode == 'menu':
            drawMenuScreen(app)
        elif app.screenmode == 'rules':
            drawRulesScreen(app)
    elif app.tag == 'game':
        if app.screenmode == 'war':
            drawWarGame(app)
        elif app.screenmode == 'blackjack':
            drawBlackjackGame(app)
        elif app.screenmode == 'gofish':
            drawGoFishGame(app)

def drawMenuScreen(app):
    drawLabel('Pick a card game below!')

def drawRulesScreen(app):
    pass

def drawWarGame(app):
    pass

def drawBlackJackGame(app):
    pass

def drawGoFishGame(app):
    pass

def main():
    runApp()

main()