# most of the test code is generated by Claude AI with edits made by me

from card import Card, Deck, Hand

# Test Card
card1 = Card('Ace', 'Spades')
print(card1)                  # Ace of Spades, face down
card1.flip()
print(card1)                  # Ace of Spades, face up

# Test faceUp parameter
card2 = Card('King', 'Hearts', True)
print(card2)                  # King of Hearts, face up

# Test Deck
deck = Deck()
print(deck)                   # Deck has 52 cards left
print(deck.cards[:5])         # 5 random cards (shuffled)

# Test unshuffled deck
deck2 = Deck(shuffled=False)
print(deck2.cards[:3])        # [2 of Hearts, 3 of Hearts, 4 of Hearts]

# Test Deal to Hand
hand = Hand()
deck.deal(hand, 5)
print(hand)                   # Hand with 5 cards
print(hand.getCount())        # 5
print(deck)                   # Deck has 47 cards left
print(deck.getCardsLeft())    # 47

# Test removeCard
removed = hand.cards[0]
hand.removeCard(removed)
print(hand.getCount())        # 4

# Test multi-deck shoe
shoe = Deck(numDecks=6)
print(shoe)                   # Deck has 312 cards left

# Test reset
shoe.deal(hand, 10)
print(shoe)                   # Deck has 302 cards left
shoe.reset()
print(shoe)                   # Deck has 312 cards left