from cmu_graphics import *
import math

# code in this file generated by Claude with edits made by me

# ============================================================
# SHARED BACKGROUND - call this in every screen's draw function
# ============================================================
def drawPokerTableBackground(app):
    # Dark wood border
    drawRect(0, 0, app.width, app.height, fill=rgb(45, 28, 16))
    
    # Green felt table
    drawRect(40, 40, app.width - 80, app.height - 80, 
             fill=rgb(30, 100, 50), border=rgb(60, 40, 20), 
             borderWidth=6)
    
    # Inner gold trim
    drawRect(52, 52, app.width - 104, app.height - 104, 
             fill=None, border=rgb(180, 140, 60), borderWidth=2)
    
    # Corner decorations
    corners = [(60, 60), (app.width - 68, 60), 
               (60, app.height - 68), (app.width - 68, app.height - 68)]
    for cx, cy in corners:
        drawPixelDiamond(cx, cy, rgb(180, 140, 60))

# ============================================================
# BLACKJACK TABLE — D-shaped half-circle table in 8-bit style
# ============================================================
def drawBlackjackTable(app):
    cx = app.width / 2

    # color palette
    bgColor   = rgb(15, 8, 4)       # near-black surround
    feltColor = rgb(22, 85, 42)     # casino green felt
    railDark  = rgb(50, 25, 6)      # dark mahogany
    railMid   = rgb(82, 46, 14)     # mid mahogany
    railLight = rgb(114, 66, 22)    # mahogany highlight
    goldColor = rgb(180, 140, 60)
    goldDim   = rgb(120, 90, 30)

    # layout
    tableTop = 18                       # top of the flat dealer rail
    railW    = 22                       # rail thickness (pixels)
    pivotY   = int(app.height * 0.30)   # y where the flat top meets the arc

    # outer D-arc semi-axes (the full rail outer edge)
    aOut = (app.width - 40) / 2
    bOut = app.height - pivotY - 18

    # inner felt D-arc semi-axes (inset by railW from the outer edge)
    aIn = aOut - railW
    bIn = bOut - railW

    # === 1. Background ===
    drawRect(0, 0, app.width, app.height, fill=bgColor)

    # === 2. Outer wood rail arc (dark base layer) ===
    # startAngle=180, sweepAngle=180: sweeps CCW from west → south → east
    # (standard math y-up convention), which renders as the bottom D-shape on screen
    drawArc(cx - aOut, pivotY - bOut, aOut * 2, bOut * 2,
            180, 180, fill=railDark)

    # mid-tone highlight strip just inside the outer edge
    aMid = aOut - 5
    bMid = bOut - 5
    drawArc(cx - aMid, pivotY - bMid, aMid * 2, bMid * 2,
            180, 180, fill=railMid)

    # === 3. Inner felt D-arc ===
    drawArc(cx - aIn, pivotY - bIn, aIn * 2, bIn * 2,
            180, 180, fill=feltColor)

    # === 4. Side rails (vertical strips left and right of the felt rect) ===
    sideTop = tableTop + railW
    sideH   = pivotY - sideTop

    # left side
    drawRect(cx - aOut, sideTop, railW, sideH, fill=railDark)
    drawRect(cx - aOut + 4, sideTop, railW - 4, sideH, fill=railMid)

    # right side
    drawRect(cx + aIn, sideTop, railW, sideH, fill=railDark)
    drawRect(cx + aIn, sideTop, railW - 4, sideH, fill=railMid)

    # === 5. Felt rectangle (upper dealer section) ===
    # extend 4px past pivotY to close any sub-pixel gap with the arc below
    drawRect(cx - aIn, sideTop, aIn * 2, sideH + 4, fill=feltColor)

    # === 6. Top flat rail (three-tone pixel layers) ===
    drawRect(cx - aOut, tableTop, aOut * 2, railW, fill=railDark)   # base
    drawRect(cx - aOut, tableTop, aOut * 2, railW - 6, fill=railMid) # mid
    drawRect(cx - aOut, tableTop, aOut * 2, 6, fill=railLight)       # top shine

    # === 7. Gold trim along inner rail edges ===
    # top rail inner edge
    drawRect(cx - aIn, tableTop + railW - 2, aIn * 2, 2, fill=goldColor)
    # left rail inner edge
    drawRect(cx - aIn - 2, sideTop, 2, sideH, fill=goldColor)
    # right rail inner edge
    drawRect(cx + aIn, sideTop, 2, sideH, fill=goldColor)

    # === 8. Pixel decorations on the top rail ===
    dotSpacing = 80
    dotY = tableTop + railW // 2
    dotStart = int(cx - aIn + dotSpacing)
    dotEnd   = int(cx + aIn - dotSpacing + 1)
    for dotX in range(dotStart, dotEnd, dotSpacing):
        _drawRailPixelDot(dotX, dotY, goldColor)

    # === 9. Chunky pixel blocks along the arc rail edge (8-bit look) ===
    # sweep matches drawArc: 180° (left) → 270° (bottom) → 360° (right)
    blockStep = 8
    midA = (aOut + aIn) / 2
    midB = (bOut + bIn) / 2
    for deg in range(180, 361, blockStep):
        rad = math.radians(deg)
        px = cx + midA * math.cos(rad)   # cos(180)=-1 (left) → cos(360)=1 (right)
        py = pivotY - midB * math.sin(rad)  # sin(270)=-1 → -(-1)=+1 → downward
        drawRect(px - 3, py - 3, 6, 6, fill=goldDim)

def _drawRailPixelDot(x, y, color):
    # 8-bit diamond shape for rail decoration
    drawRect(x - 2, y - 4, 4, 2, fill=color)
    drawRect(x - 4, y - 2, 8, 4, fill=color)
    drawRect(x - 2, y + 2, 4, 2, fill=color)


def drawPixelDiamond(x, y, color):
    # 8-bit style diamond made of small squares
    drawRect(x + 4, y, 4, 4, fill=color)       # top
    drawRect(x, y + 4, 4, 4, fill=color)       # left
    drawRect(x + 4, y + 4, 4, 4, fill=color)   # center
    drawRect(x + 8, y + 4, 4, 4, fill=color)   # right
    drawRect(x + 4, y + 8, 4, 4, fill=color)   # bottom


# ============================================================
# 8-BIT TEXT RENDERING
# ============================================================
def drawPixelText(text, centerX, centerY, color, scale=1):
    # Uses cmu_graphics built-in text but with a blocky font style
    # For true 8-bit feel, we draw a shadow behind the text
    shadowOffset = max(2, 2 * scale)
    
    # Shadow
    drawLabel(text, centerX + shadowOffset, centerY + shadowOffset, 
              size=16 * scale, bold=True, fill=rgb(0, 0, 0), opacity=50,
              font='monospace')
    # Main text
    drawLabel(text, centerX, centerY, 
              size=16 * scale, bold=True, fill=color,
              font='monospace')


# ============================================================
# DECORATIVE CARD SPRITES (8-bit style mini cards)
# ============================================================
def drawMiniCard(x, y, suit):
    drawRect(x, y, 22, 30, fill='white', border=rgb(60,60,60), borderWidth=1)
    symbols = {'heart': '♥', 'diamond': '♦', 'spade': '♠', 'club': '♣'}
    colors = {'heart': 'red', 'diamond': 'red', 'spade': 'black', 'club': 'black'}
    drawLabel(symbols[suit], x + 11, y + 15, size=18, fill=colors[suit], bold=True)


# ============================================================
# MENU SCREEN
# ============================================================
def drawMenuScreen(app):
    drawPokerTableBackground(app)
    
    # Title banner background (pixelated banner shape)
    drawRect(120, 100, 560, 60, fill=rgb(140, 20, 20))
    drawRect(124, 104, 552, 52, fill=rgb(180, 30, 30))
    # Pixel border effect on banner
    drawRect(120, 100, 560, 4, fill=rgb(200, 160, 50))
    drawRect(120, 156, 560, 4, fill=rgb(200, 160, 50))
    drawRect(120, 100, 4, 60, fill=rgb(200, 160, 50))
    drawRect(676, 100, 4, 60, fill=rgb(200, 160, 50))
    
    # Title text
    drawPixelText('WELCOME TO CARD GAME SUITE', app.width / 2, 130, 
                  rgb(255, 230, 150), scale=1.5)
    
    # Subtitle
    drawPixelText('please select a game below!', app.width / 2, 195, 
                  rgb(200, 200, 180), scale=1)
    
    # Decorative chip icons next to subtitle
    drawPixelChip(app.width/2 - 180, 188, rgb(200, 50, 50))
    drawPixelChip(app.width/2 + 168, 188, rgb(50, 50, 200))

    # Decorative cards scattered around the title
    drawMiniCard(135, 115, 'heart')
    drawMiniCard(165, 115, 'spade')
    drawMiniCard(605, 115, 'diamond')
    drawMiniCard(635, 115, 'club')
    
    # Footer text
    drawPixelText('press R for rules', app.width / 2, 535, 
                  rgb(150, 150, 130), scale=0.8)
    
    # Decorative bottom cards
    # Bottom left
    drawMiniCard(80, 480, 'club')
    drawMiniCard(110, 490, 'heart')

    # Bottom right (mirrored)
    drawMiniCard(app.width - 132, 490, 'diamond')
    drawMiniCard(app.width - 102, 480, 'spade')

def drawPixelChip(x, y, color):
    # Simple 8-bit poker chip (circle made of squares)
    drawRect(x + 4, y, 8, 4, fill=color)
    drawRect(x, y + 4, 16, 8, fill=color)
    drawRect(x + 4, y + 12, 8, 4, fill=color)
    # Center dot
    drawRect(x + 6, y + 6, 4, 4, fill='white')