from cmu_graphics import *

# code in this file generated by Claude with edits made by me

# ============================================================
# SHARED TABLE BACKGROUND — used by all screens as the base layer
# ============================================================
def drawTableBackground(app):
    bgColor   = rgb(15, 8, 4)
    feltColor = rgb(22, 85, 42)
    railDark  = rgb(50, 25, 6)
    railMid   = rgb(82, 46, 14)
    railLight = rgb(114, 66, 22)
    goldColor = rgb(180, 140, 60)
    goldDim   = rgb(120, 90, 30)

    railW  = 22
    border = 20   # outer dark wood margin

    # outer rail box
    ox = border
    oy = border
    ow = app.width  - border * 2
    oh = app.height - border * 2

    # inner felt box (inset by railW)
    fx = ox + railW
    fy = oy + railW
    fw = ow - railW * 2
    fh = oh - railW * 2

    # background
    drawRect(0, 0, app.width, app.height, fill=bgColor)

    # wood rail — three-tone layered rectangles
    drawRect(ox, oy, ow, oh, fill=railDark)
    drawRect(ox + 4, oy + 4, ow - 8, oh - 8, fill=railMid)
    drawRect(ox + 4, oy + 4, ow - 8, 6, fill=railLight)   # top shine strip

    # green felt
    drawRect(fx, fy, fw, fh, fill=feltColor)

    # gold inner trim (four sides)
    drawRect(fx, fy, fw, 2, fill=goldColor)
    drawRect(fx, fy + fh - 2, fw, 2, fill=goldColor)
    drawRect(fx, fy, 2, fh, fill=goldColor)
    drawRect(fx + fw - 2, fy, 2, fh, fill=goldColor)

    # gold corner diamonds
    for dx, dy in [(fx + 6, fy + 6), (fx + fw - 18, fy + 6),
                   (fx + 6, fy + fh - 18), (fx + fw - 18, fy + fh - 18)]:
        drawPixelDiamond(dx, dy, goldDim)

    # pixel dot decorations along the top rail
    dotSpacing = 80
    dotY = oy + railW // 2
    for dotX in range(int(fx + dotSpacing), int(fx + fw - dotSpacing + 1), dotSpacing):
        _drawRailPixelDot(dotX, dotY, goldColor)

def _drawRailPixelDot(x, y, color):
    # 8-bit diamond shape for rail decoration
    drawRect(x - 2, y - 4, 4, 2, fill=color)
    drawRect(x - 4, y - 2, 8, 4, fill=color)
    drawRect(x - 2, y + 2, 4, 2, fill=color)


def drawPixelDiamond(x, y, color):
    # 8-bit style diamond made of small squares
    drawRect(x + 4, y, 4, 4, fill=color)       # top
    drawRect(x, y + 4, 4, 4, fill=color)       # left
    drawRect(x + 4, y + 4, 4, 4, fill=color)   # center
    drawRect(x + 8, y + 4, 4, 4, fill=color)   # right
    drawRect(x + 4, y + 8, 4, 4, fill=color)   # bottom


# ============================================================
# 8-BIT TEXT RENDERING
# ============================================================
def drawPixelText(text, centerX, centerY, color, scale=1):
    # Uses cmu_graphics built-in text but with a blocky font style
    # For true 8-bit feel, we draw a shadow behind the text
    shadowOffset = max(2, 2 * scale)
    
    # Shadow
    drawLabel(text, centerX + shadowOffset, centerY + shadowOffset, 
              size=16 * scale, bold=True, fill=rgb(0, 0, 0), opacity=50,
              font='monospace')
    # Main text
    drawLabel(text, centerX, centerY, 
              size=16 * scale, bold=True, fill=color,
              font='monospace')


# ============================================================
# DECORATIVE CARD SPRITES (8-bit style mini cards)
# ============================================================
def drawMiniCard(x, y, suit):
    drawRect(x, y, 22, 30, fill='white', border=rgb(60,60,60), borderWidth=1)
    symbols = {'heart': '♥', 'diamond': '♦', 'spade': '♠', 'club': '♣'}
    colors = {'heart': 'red', 'diamond': 'red', 'spade': 'black', 'club': 'black'}
    drawLabel(symbols[suit], x + 11, y + 15, size=18, fill=colors[suit], bold=True)


# ============================================================
# MENU SCREEN
# ============================================================
def drawMenuScreen(app):
    drawTableBackground(app)
    
    # Title banner background (pixelated banner shape)
    drawRect(120, 100, 560, 60, fill=rgb(140, 20, 20))
    drawRect(124, 104, 552, 52, fill=rgb(180, 30, 30))
    # Pixel border effect on banner
    drawRect(120, 100, 560, 4, fill=rgb(200, 160, 50))
    drawRect(120, 156, 560, 4, fill=rgb(200, 160, 50))
    drawRect(120, 100, 4, 60, fill=rgb(200, 160, 50))
    drawRect(676, 100, 4, 60, fill=rgb(200, 160, 50))
    
    # Title text
    drawPixelText('WELCOME TO CARD GAME SUITE', app.width / 2, 130, 
                  rgb(255, 230, 150), scale=1.5)
    
    # Subtitle
    drawPixelText('please select a game below!', app.width / 2, 195, 
                  rgb(200, 200, 180), scale=1)
    
    # Decorative chip icons next to subtitle
    drawPixelChip(app.width/2 - 180, 188, rgb(200, 50, 50))
    drawPixelChip(app.width/2 + 168, 188, rgb(50, 50, 200))

    # Decorative cards scattered around the title
    drawMiniCard(135, 115, 'heart')
    drawMiniCard(165, 115, 'spade')
    drawMiniCard(605, 115, 'diamond')
    drawMiniCard(635, 115, 'club')
    
    # Footer text
    drawPixelText('press R for rules', app.width / 2, 535, 
                  rgb(150, 150, 130), scale=0.8)
    
    # Decorative bottom cards
    # Bottom left
    drawMiniCard(80, 480, 'club')
    drawMiniCard(110, 490, 'heart')

    # Bottom right (mirrored)
    drawMiniCard(app.width - 132, 490, 'diamond')
    drawMiniCard(app.width - 102, 480, 'spade')

def drawPixelChip(x, y, color):
    # Simple 8-bit poker chip (circle made of squares)
    drawRect(x + 4, y, 8, 4, fill=color)
    drawRect(x, y + 4, 16, 8, fill=color)
    drawRect(x + 4, y + 12, 8, 4, fill=color)
    # Center dot
    drawRect(x + 6, y + 6, 4, 4, fill='white')